In [246]:
import pandas as pd
import numpy as np
import statistics

In [247]:
df = pd.read_json("C:/Users/VINAYTEJA KEASRI/OneDrive/Desktop/AIRBNB/Airbnb.json")

In [248]:
df.to_csv('Airbng.csv', index=False)

In [249]:
df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '4351675', 'date': '2013-04-29 04:00:...",NaN,NaN,NaN
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '52004703', 'host_url': 'https://w...","{'street': 'Fatih , İstanbul, Turkey', 'suburb...","{'availability_30': 30, 'availability_60': 60,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '149469150', 'date': '2017-05-04 04:0...",NaN,NaN,NaN
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51624384', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '56904633', 'date': '2015-12-19 05:00...",5000.0,NaN,NaN
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51744313', 'host_url': 'https://w...","{'street': 'Hong Kong , 九龍, Hong Kong', 'subur...","{'availability_30': 14, 'availability_60': 24,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '57191745', 'date': '2015-12-22 05:00...",1350.0,5000.0,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '13764143', 'host_url': 'https://w...","{'street': 'Surry Hills, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '123549502', 'date': '2016-12-29 05:0...",NaN,NaN,NaN

In [250]:
df.shape

(5555, 42)

In [251]:
df.info

<bound method DataFrame.info of            _id                            listing_url  \
0      1003530   https://www.airbnb.com/rooms/1003530
1     10133554  https://www.airbnb.com/rooms/10133554
2     10059872  https://www.airbnb.com/rooms/10059872
3     10084023  https://www.airbnb.com/rooms/10084023
4     10091713  https://www.airbnb.com/rooms/10091713
...        ...                                    ...
5550   9985696   https://www.airbnb.com/rooms/9985696
5551   9993190   https://www.airbnb.com/rooms/9993190
5552   9887054   https://www.airbnb.com/rooms/9887054
5553   9907907   https://www.airbnb.com/rooms/9907907
5554   9936016   https://www.airbnb.com/rooms/9936016

                                                   name  \
0                   New York City - Upper West Side Apt
1                   Double and triple rooms Blue mosque
2                    Soho Cozy, Spacious and Convenient
3                     City center private room with bed
4      Surry Hills Studio - Your Perfect Base in Sydney
...                                                 ...
5550                                    Kadıköy-Altıyol
5551  Just Steps from the Ocean at Premier Platinum ...
5552                Quarry Bay fully furnished studio C
5553                         Large double room in Bondi
5554                        Alugo Apartamento na Tijuca

                                                summary  \
0
1
2     Clean, fully furnish, Spacious 1 bedroom flat ...
3     House is located 5mins walk from Sham Shui Po ...
4     This spacious, light filled studio has everyth...
...                                                 ...
5550  Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...
5551  Relax Hawaiian Style in Gated Community on Oce...
5552   Newly renovated studio flat with full furniture.
5553  A bright large double room is available in a b...
5554  Apartamento amplo que acomoda 6 pessoas. Um qu...

                                                  space  \
0     Murphy bed, optional second bedroom available....
1     We are on the central city  Blue mosque 5 minu...
2
3     The house is old fashion type, and paint the w...
4     Comfortable studio with a great layout. The ba...
...                                                 ...
5550
5551  ***NOTE: THE OCEAN INFINITY POOL ("POOL 1"0 WI...
5552
5553
5554

                                            description  \
0     Murphy bed, optional second bedroom available....
1     We are on the central city  Blue mosque 5 minu...
2     Clean, fully furnish, Spacious 1 bedroom flat ...
3     House is located 5mins walk from Sham Shui Po ...
4     This spacious, light filled studio has everyth...
...                                                 ...
5550  Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...
5551  Relax Hawaiian Style in Gated Community on Oce...
5552   Newly renovated studio flat with full furniture.
5553  A bright large double room is available in a b...
5554  Apartamento amplo que acomoda 6 pessoas. Um qu...

                                  neighborhood_overview  \
0     Great neighborhood - many terrific restaurants...
1     Cankurtaran mahallesi akbıyık caddesi no 22 Su...
2
3     Cheapest food, electronic device, clothing and...
4     Surry Hills is a vibrant eclectic community an...
...                                                 ...
5550
5551  Location: Located at the south end of Lahaina ...
5552
5553
5554

                                                  notes  \
0     My cat, Samantha, are in and out during the su...
1
2
3     Deposit of $1000 will be charged and will retu...
4     WiFi, Apple TV with Netflix App (for use with ...
...                                                 ...
5550
5551  Puamana Resort requires a $10/day resort fee w...
5552
5553
5554

                                                transit  \
0     Conveniently located near 1, 2, 3, B & C subwa...
1      Tram 5 minutes  metro 10 minutes  Bus 10 minutes
2
3     Close to 3 different MTR Station, Sham shui Po...
4     Travel Card 'Opal' travel cards work on all Sy...
...                                                 ...
5550
5551  You can walk to most attractions within Lahain...
5552
5553  The flat is exactly half way between the shops...
5554

                                                 access  ... guests_included  \
0                                        New York City!  ...               1
1     We have bathroom,wc,İnternet in rooms and unde...  ...               1
2                                                        ...               1
3     Living Room , Kitchen and Toilet, All cooking ...  ...               1
4     You have full use of the entire studio and com...  ...               1
...                                                 ...  ...             ...
5550                                                     ...               1
5551  Guests will have access to the 3 pools in the ...  ...               1
5552                                                     ...               2
5553  Guests will have access to the full residence,...  ...               2
5554                                                     ...               1

                                                 images  \
0     {'thumbnail_url': '', 'medium_url': '', 'pictu...
1     {'thumbnail_url': '', 'medium_url': '', 'pictu...
2     {'thumbnail_url': '', 'medium_url': '', 'pictu...
3     {'thumbnail_url': '', 'medium_url': '', 'pictu...
4     {'thumbnail_url': '', 'medium_url': '', 'pictu...
...                                                 ...
5550  {'thumbnail_url': '', 'medium_url': '', 'pictu...
5551  {'thumbnail_url': '', 'medium_url': '', 'pictu...
5552  {'thumbnail_url': '', 'medium_url': '', 'pictu...
5553  {'thumbnail_url': '', 'medium_url': '', 'pictu...
5554  {'thumbnail_url': '', 'medium_url': '', 'pictu...

                                                   host  \
0     {'host_id': '454250', 'host_url': 'https://www...
1     {'host_id': '52004703', 'host_url': 'https://w...
2     {'host_id': '51624384', 'host_url': 'https://w...
3     {'host_id': '51744313', 'host_url': 'https://w...
4     {'host_id': '13764143', 'host_url': 'https://w...
...                                                 ...
5550  {'host_id': '51303748', 'host_url': 'https://w...
5551  {'host_id': '51013381', 'host_url': 'https://w...
5552  {'host_id': '31386255', 'host_url': 'https://w...
5553  {'host_id': '47615848', 'host_url': 'https://w...
5554  {'host_id': '47092481', 'host_url': 'https://w...

                                                address  \
0     {'street': 'New York, NY, United States', 'sub...
1     {'street': 'Fatih , İstanbul, Turkey', 'suburb...
2     {'street': 'Hong Kong, Hong Kong Island, Hong ...
3     {'street': 'Hong Kong , 九龍, Hong Kong', 'subur...
4     {'street': 'Surry Hills, NSW, Australia', 'sub...
...                                                 ...
5550  {'street': 'Kadıköy, İstanbul, Turkey', 'subur...
5551  {'street': 'Lahaina, HI, United States', 'subu...
5552  {'street': 'Hong Kong, Hong Kong Island, Hong ...
5553  {'street': 'Bondi Beach, NSW, Australia', 'sub...
5554  {'street': 'Rio de Janeiro, Rio de Janeiro, Br...

                                           availability  \
0     {'availability_30': 0, 'availability_60': 0, '...
1     {'availability_30': 30, 'availability_60': 60,...
2     {'availability_30': 0, 'availability_60': 0, '...
3     {'availability_30': 14, 'availability_60': 24,...
4     {'availability_30': 0, 'availability_60': 0, '...
...                                                 ...
5550  {'availability_30': 30, 'availability_60': 60,...
5551  {'availability_30': 0, 'availability_60': 8, '...
5552  {'availability_30': 18, 'availability_60': 48,...
5553  {'availability_30': 0, 'availability_60': 0, '...
5554  {'availability_30': 0, 'availability_60': 0, '...

                                          review_scores  \
0     {'review_scores_accuracy': 10, 'review_scores_...
1     {'review_scores_accuracy': 9, 'review_scores_c...
2     {'review_scores_accuracy': 10, 'review_scores_...
3     {'review_scores_accuracy': 10, 'review_scores_...
4     {'review_scores_accuracy': 10, 'review_scores_...
...                                                 ...
5550                                                 {}
5551  {'review_scores_accuracy': 10, 'review_scores_...
5552  {'review_scores_accuracy': 10, 'review_scores_...
5553                                                 {}
5554                                                 {}

                                                reviews weekly_price  \
0     [{'_id': '4351675', 'date': '2013-04-29 04:00:...          NaN
1     [{'_id': '149469150', 'date': '2017-05-04 04:0...          NaN
2     [{'_id': '56904633', 'date': '2015-12-19 05:00...       5000.0
3     [{'_id': '57191745', 'date': '2015-12-22 05:00...       1350.0
4     [{'_id': '123549502', 'date': '2016-12-29 05:0...          NaN
...                                                 ...          ...
5550                                                 []          NaN
5551  [{'_id': '68762225', 'date': '2016-04-06 04:00...          NaN
5552  [{'_id': '105800033', 'date': '2016-10-02 04:0...          NaN
5553                                                 []          NaN
5554                                                 []          NaN

     monthly_price reviews_per_month
0              NaN               NaN
1              NaN               NaN
2              NaN               NaN
3           5000.0               NaN
4              NaN               NaN
...            ...               ...
5550           NaN               NaN
5551           NaN               NaN
5552           NaN               NaN
5553           NaN               NaN
5554           NaN               NaN

[5555 rows x 42 columns]>

In [252]:
df.isnull().sum()

_id                         0
listing_url                 0
name                        0
summary                     0
space                       0
description                 0
neighborhood_overview       0
notes                       0
transit                     0
access                      0
interaction                 0
house_rules                 0
property_type               0
room_type                   0
bed_type                    0
minimum_nights              0
maximum_nights              0
cancellation_policy         0
last_scraped                0
calendar_last_scraped       0
first_review             1388
last_review              1388
accommodates                0
bedrooms                    5
beds                       13
number_of_reviews           0
bathrooms                  10
amenities                   0
price                       0
security_deposit         2084
cleaning_fee             1531
extra_people                0
guests_included             0
images                      0
host                        0
address                     0
availability                0
review_scores               0
reviews                     0
weekly_price             4841
monthly_price            4899
reviews_per_month        5461
dtype: int64

In [253]:
df.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'host', 'address',
       'availability', 'review_scores', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month'],
      dtype='object')

In [254]:
# List of columns to check for NaN values
columns_to_check = [
    '_id', 'name', 'property_type', 'room_type', 'bed_type',
    'minimum_nights', 'maximum_nights', 'cancellation_policy',
    'accommodates', 'bedrooms', 'beds', 'bathrooms', 'amenities', 'price',
    'security_deposit', 'cleaning_fee', 'extra_people', 'guests_included',
    'address', 'review_scores'
]

# Check for NaN values in the specified columns
nan_values = df[columns_to_check].isna().sum()

# Display the number of NaN values in each column
print(nan_values)

_id                       0
name                      0
property_type             0
room_type                 0
bed_type                  0
minimum_nights            0
maximum_nights            0
cancellation_policy       0
accommodates              0
bedrooms                  5
beds                     13
bathrooms                10
amenities                 0
price                     0
security_deposit       2084
cleaning_fee           1531
extra_people              0
guests_included           0
address                   0
review_scores             0
dtype: int64

In [255]:
# List of columns to remove
columns_to_remove = [
    'listing_url',
    'summary',                   
    'space',                     
    'description',               
    'neighborhood_overview',     
    'notes',                     
    'transit',                   
    'access',                    
    'interaction',               
    'house_rules',
    'last_scraped',              
    'calendar_last_scraped',     
    'first_review',              
    'last_review', 
    'number_of_reviews',
    'images',                    
    'host',
    'reviews',                   
    'weekly_price',              
    'monthly_price',             
    'reviews_per_month',
    'availability'
]

# Remove the columns from the DataFrame
df.drop(columns=columns_to_remove, inplace=True)

In [256]:
df['security_deposit'].fillna(df['security_deposit'].median(), inplace=True)

In [257]:
df['cleaning_fee'].fillna(df['cleaning_fee'].median(), inplace=True)

In [258]:
df['extra_people'].fillna(df['extra_people'].median(), inplace=True)

In [259]:
df['bedrooms'].fillna(df['bedrooms'].mode().iloc[0],inplace=True)

In [260]:
df['beds'].fillna(df['beds'].mode().iloc[0],inplace=True)

In [261]:
df['bathrooms'].fillna(df['bathrooms'].mode().iloc[0],inplace=True)

In [262]:
df.dropna(subset=['bathrooms'],inplace=True)

In [263]:
df.isnull().sum()

_id                    0
name                   0
property_type          0
room_type              0
bed_type               0
minimum_nights         0
maximum_nights         0
cancellation_policy    0
accommodates           0
bedrooms               0
beds                   0
bathrooms              0
amenities              0
price                  0
security_deposit       0
cleaning_fee           0
extra_people           0
guests_included        0
address                0
review_scores          0
dtype: int64

In [264]:
df['address'].values

array([{'street': 'New York, NY, United States', 'suburb': 'Manhattan', 'government_area': 'Upper West Side', 'market': 'New York', 'country': 'United States', 'country_code': 'US', 'location': {'type': 'Point', 'coordinates': [-73.96523, 40.79962], 'is_location_exact': False}},
       {'street': 'Fatih , İstanbul, Turkey', 'suburb': 'Fatih', 'government_area': 'Fatih', 'market': 'Istanbul', 'country': 'Turkey', 'country_code': 'TR', 'location': {'type': 'Point', 'coordinates': [28.98009, 41.0062], 'is_location_exact': False}},
       {'street': 'Hong Kong, Hong Kong Island, Hong Kong', 'suburb': 'Central & Western District', 'government_area': 'Central & Western', 'market': 'Hong Kong', 'country': 'Hong Kong', 'country_code': 'HK', 'location': {'type': 'Point', 'coordinates': [114.15027, 22.28158], 'is_location_exact': True}},
       ...,
       {'street': 'Hong Kong, Hong Kong Island, Hong Kong', 'suburb': 'Quarry Bay', 'government_area': 'Eastern', 'market': 'Hong Kong', 'country': 'Hong Kong', 'country_code': 'HK', 'location': {'type': 'Point', 'coordinates': [114.20722, 22.29157], 'is_location_exact': False}},
       {'street': 'Bondi Beach, NSW, Australia', 'suburb': 'Bondi', 'government_area': 'Waverley', 'market': 'Sydney', 'country': 'Australia', 'country_code': 'AU', 'location': {'type': 'Point', 'coordinates': [151.26542, -33.89298], 'is_location_exact': False}},
       {'street': 'Rio de Janeiro, Rio de Janeiro, Brazil', 'suburb': 'Lapa', 'government_area': 'Centro', 'market': 'Rio De Janeiro', 'country': 'Brazil', 'country_code': 'BR', 'location': {'type': 'Point', 'coordinates': [-43.173761316748546, -22.90833634089244], 'is_location_exact': False}}],
      dtype=object)

In [265]:
df['address'] = df['address'].astype(str)

In [266]:
import ast

df['street'] = df['address'].apply(lambda x: ast.literal_eval(x)['street'])

In [267]:
df['suburb'] = df['address'].apply(lambda x: ast.literal_eval(x)['suburb'])
df['government_area'] = df['address'].apply(lambda x: ast.literal_eval(x)['government_area'])
df['market'] = df['address'].apply(lambda x: ast.literal_eval(x)['market'])
df['country'] = df['address'].apply(lambda x: ast.literal_eval(x)['country'])
df['country_code'] = df['address'].apply(lambda x: ast.literal_eval(x)['country_code'])
df['location'] = df['address'].apply(lambda x: ast.literal_eval(x)['location'])

df['location_type'] = df['address'].apply(lambda x: ast.literal_eval(x)['location']['type'])
df['location_exact'] = df['address'].apply(lambda x: ast.literal_eval(x)['location']['is_location_exact'])
df['location_coordinate'] = df['address'].apply(lambda x: ast.literal_eval(x)['location']['coordinates'])

In [268]:
# Check for null values in each address column
address_columns = ['street', 'suburb', 'government_area', 'market', 'country', 'country_code', 'location_type', 'location_exact', 'location_coordinate']

for column in address_columns:
    null_count = df[column].isnull().sum()
    print(f"{column}: {null_count} null values")

street: 0 null values
suburb: 0 null values
government_area: 0 null values
market: 0 null values
country: 0 null values
country_code: 0 null values
location_type: 0 null values
location_exact: 0 null values
location_coordinate: 0 null values

In [269]:
df['review_scores'].values

array([{'review_scores_accuracy': 10, 'review_scores_cleanliness': 9, 'review_scores_checkin': 10, 'review_scores_communication': 10, 'review_scores_location': 10, 'review_scores_value': 10, 'review_scores_rating': 94},
       {'review_scores_accuracy': 9, 'review_scores_cleanliness': 9, 'review_scores_checkin': 10, 'review_scores_communication': 10, 'review_scores_location': 10, 'review_scores_value': 9, 'review_scores_rating': 92},
       {'review_scores_accuracy': 10, 'review_scores_cleanliness': 10, 'review_scores_checkin': 10, 'review_scores_communication': 10, 'review_scores_location': 10, 'review_scores_value': 8, 'review_scores_rating': 100},
       ...,
       {'review_scores_accuracy': 10, 'review_scores_cleanliness': 9, 'review_scores_checkin': 10, 'review_scores_communication': 10, 'review_scores_location': 10, 'review_scores_value': 9, 'review_scores_rating': 85},
       {}, {}], dtype=object)

In [270]:
df.columns

Index(['_id', 'name', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'accommodates', 'bedrooms', 'beds', 'bathrooms', 'amenities', 'price',
       'security_deposit', 'cleaning_fee', 'extra_people', 'guests_included',
       'address', 'review_scores', 'street', 'suburb', 'government_area',
       'market', 'country', 'country_code', 'location', 'location_type',
       'location_exact', 'location_coordinate'],
      dtype='object')

In [271]:
df['review_scores_accuracy'] = df['review_scores'].apply(lambda x: x.get('review_scores_accuracy', None))

In [272]:
df['review_scores_cleanliness'] = df['review_scores'].apply(lambda x: x.get('review_scores_cleanliness', None))

In [273]:
df['review_scores_checkin'] = df['review_scores'].apply(lambda x: x.get('review_scores_checkin', None))

In [274]:
df['review_scores_communication'] = df['review_scores'].apply(lambda x: x.get('review_scores_communication', None))

In [275]:
df['review_scores_location'] = df['review_scores'].apply(lambda x: x.get('review_scores_location', None))

In [276]:
df['review_scores_value'] = df['review_scores'].apply(lambda x: x.get('review_scores_value', None))

In [277]:
df['review_scores_rating'] = df['review_scores'].apply(lambda x: x.get('review_scores_rating', None))

In [278]:
review_scores_columns = ['review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location',
                        'review_scores_value','review_scores_rating']
for column in review_scores_columns:
    null_count = df[column].isnull().sum()
    print(f"{column}: {null_count} null values")

review_scores_accuracy: 1476 null values
review_scores_cleanliness: 1473 null values
review_scores_checkin: 1475 null values
review_scores_communication: 1474 null values
review_scores_location: 1474 null values
review_scores_value: 1475 null values
review_scores_rating: 1474 null values

In [279]:

df.dropna(subset=['review_scores_accuracy', 
                  'review_scores_cleanliness',
                  'review_scores_checkin', 
                  'review_scores_communication', 
                  'review_scores_location',
                  'review_scores_value',
                  'review_scores_rating'], inplace=True)

In [280]:
# Fill with the mean of each column
df['review_scores_accuracy'].fillna(df['review_scores_accuracy'].mean(), inplace=True)
df['review_scores_cleanliness'].fillna(df['review_scores_cleanliness'].mean(), inplace=True)
df['review_scores_checkin'].fillna(df['review_scores_checkin'].mean(), inplace=True)
df['review_scores_communication'].fillna(df['review_scores_communication'].mean(), inplace=True)
df['review_scores_location'].fillna(df['review_scores_location'].mean(), inplace=True)
df['review_scores_value'].fillna(df['review_scores_value'].mean(), inplace=True)
df['review_scores_rating'].fillna(df['review_scores_rating'].mean(), inplace=True)

In [281]:
df.isnull().sum()

_id                            0
name                           0
property_type                  0
room_type                      0
bed_type                       0
minimum_nights                 0
maximum_nights                 0
cancellation_policy            0
accommodates                   0
bedrooms                       0
beds                           0
bathrooms                      0
amenities                      0
price                          0
security_deposit               0
cleaning_fee                   0
extra_people                   0
guests_included                0
address                        0
review_scores                  0
street                         0
suburb                         0
government_area                0
market                         0
country                        0
country_code                   0
location                       0
location_type                  0
location_exact                 0
location_coordinate            0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
review_scores_rating           0
dtype: int64

In [282]:
df = df.drop(columns=['address'])

In [283]:
df.head()

,_id,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,...,location_type,location_exact,location_coordinate,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,...,Point,False,"[-73.96523, 40.79962]",10.0,9.0,10.0,10.0,10.0,10.0,94.0
1,10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1.0,...,Point,False,"[28.98009, 41.0062]",9.0,9.0,10.0,10.0,10.0,9.0,92.0
2,10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,...,Point,True,"[114.15027, 22.28158]",10.0,10.0,10.0,10.0,10.0,8.0,100.0
3,10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1.0,...,Point,True,"[114.1669, 22.3314]",10.0,8.0,10.0,10.0,10.0,10.0,92.0
4,10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0.0,...,Point,True,"[151.21554, -33.88029]",10.0,9.0,10.0,10.0,10.0,9.0,95.0

In [284]:
df.isnull().sum()

_id                            0
name                           0
property_type                  0
room_type                      0
bed_type                       0
minimum_nights                 0
maximum_nights                 0
cancellation_policy            0
accommodates                   0
bedrooms                       0
beds                           0
bathrooms                      0
amenities                      0
price                          0
security_deposit               0
cleaning_fee                   0
extra_people                   0
guests_included                0
review_scores                  0
street                         0
suburb                         0
government_area                0
market                         0
country                        0
country_code                   0
location                       0
location_type                  0
location_exact                 0
location_coordinate            0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
review_scores_rating           0
dtype: int64

In [286]:
df.to_csv("Cleandataset.csv",index=False)